#include <iostream>
#include <clocale>
#include <string>
#include <cstring>
#include <cfloat>

using namespace std;

class Sunshine {

public:
    string weatherReport(int TD, int RD) {

        string resp;
        int SD = TD - RD;

        for (int i=0; i < TD; i++) {
            if (SD > RD)
                resp += 'S';
            else
                resp += 'R';
        }
        int temp = 0;
        int cont = 0;
        float frac = 1.0 / RD;
        cout << frac << endl;
        if (SD > RD) {
            int i = (TD / (RD + 1));
            while (i < TD) {
                resp.replace(i,1,"R");
                cout << (i - temp) << " - ";
                temp = i;
                frac += (1.0 / RD);
                if (frac < (((float) TD / RD) - (TD / RD)))
                    i += (TD / (RD+1));
                else
                    i += (TD / (RD+1))+1;
                cont++;
            }
        } else
            for (int i=(TD / (SD + 1)); i < TD; i += (TD / (SD+1))+1)
                resp.replace(i,1,"S");

        cout << cont << endl;
        cout << ((TD / RD) - ((int) (TD / RD))) << endl;
        return resp;
    }

};



int main(int argc, char* argv[])
{
	setlocale(LC_ALL, "portuguese-brazilian");

    Sunshine S;

    string fim;

    string correta = "SSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSSRSSSSSSSSSSSS";
    string teste = "não";
    fim = S.weatherReport(6,1);

    if (correta.compare(fim) == 0) teste = "sim";
    cout << teste << endl;
    cout << "Resposta: " << fim << endl;


	return 0;
}
